### ISSUE TITLE
Event loop policies are deprecated in Python 3.14 and removed in Python 3.16

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#4089]
The deprecation warning is masked for now, but it will stop working in Python 3.16. This will be a problem for Windows only.

The relevant code:

```python
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

The failing test (if code removed):

```
FAILED tests/workflows/test_execute.py::test_execute_workflow_results_with_report[path1] - sphinx.errors.ExtensionError: Notebook execution failed (exception: Proactor event loop does not implement add_reader family of methods required for zmq. Registering an additional selector thread for add_reader support via tornado. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to avoid this warning.)
```

Upstream question to pyzmq:

https://github.com/zeromq/pyzmq/issues/2137
