### ISSUE TITLE
TypeError: ModelSearchResults.__init__() got an unexpected keyword argument 'final_model_name'

### ISSUE THREAD

**Issue by sardnar** [pharmpy/pharmpy#2330]
### Bug report

Hi,

Thank you for the great software. I have run `run_modelsearch()` but I cannot re-read the results back again in newer versions of pharmpy. the following code will fail 
```
from pharmpy import tools
from pharmpy import modeling
res = tools.read_results("modelsearch_dir25/results.json")

# #TypeError: ModelSearchResults.__init__() got an unexpected keyword argument 'final_model_name'
```
This used to work on pharmpy older versions (0.99)

Python: 3.11 in conda 
OS: linux
pharmpy: 0.104

**Comment by stellabelin** [comment]
Hi! Thanks for reporting this issue! The result file is not back compatible, the attribute was renamed to `final_model`. As a manual workaround you can open results.json and change `final_model_name` to `final_model`, but we should fix this so older results can still be read in.
